name: 🔄 Dependency Updates

on:
  schedule:
    - cron: '0 4 * * 1' # Weekly on Monday at 4 AM
  workflow_dispatch:

jobs:
  # 📦 Update Dependencies
  update-dependencies:
    name: 📦 Update Dependencies
    runs-on: ubuntu-latest
    timeout-minutes: 15
    
    steps:
      - name: 📦 Checkout code
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: 📦 Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18.x'
          cache: 'npm'

      - name: 📦 Update dependencies
        run: |
          npm update
          npm audit fix --force || true

      - name: 🧪 Run tests after update
        run: |
          npm ci --legacy-peer-deps
          npm test -- --watchAll=false
        continue-on-error: true

      - name: 📋 Generate update report
        run: |
          npm outdated > outdated.txt || true
          npm ls --depth=0 > dependencies.txt

      - name: 🔄 Create Pull Request
        uses: peter-evans/create-pull-request@v5
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: '📦 Update dependencies'
          title: '📦 Weekly Dependency Updates'
          body: |
            🔄 **Automated Dependency Update**
            
            This PR contains the weekly dependency updates.
            
            ## Changes
            - Updated npm dependencies to latest compatible versions
            - Applied security fixes where available
            
            ## Testing
            - [x] Automated tests passed
            - [ ] Manual testing required
            
            Please review the changes and merge if everything looks good.
          branch: dependency-updates/weekly
          delete-branch: true

  # 🔒 Security Updates
  security-updates:
    name: 🔒 Security Updates
    runs-on: ubuntu-latest
    timeout-minutes: 10
    
    steps:
      - name: 📦 Checkout code
        uses: actions/checkout@v4

      - name: 📦 Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18.x'
          cache: 'npm'

      - name: 🔒 Security audit and fix
        run: |
          npm audit --audit-level=moderate
          npm audit fix --force || true

      - name: 🔒 Check for remaining vulnerabilities
        run: |
          npm audit --audit-level=high --production
        continue-on-error: true

      - name: 📋 Generate security report
        run: |
          npm audit --json > security-report.json || true
          
      - name: 📊 Upload security report
        uses: actions/upload-artifact@v4
        with:
          name: security-report
          path: security-report.json
          retention-days: 30